FROM alpine:edge

ENV APP "web"
ENV DEPLOY_PATH "/usr/lib/${APP}"
ENV WEB_PORT "80"
RUN echo '@edge http://nl.alpinelinux.org/alpine/edge/main' >> /etc/apk/repositories \
        && echo '@community http://nl.alpinelinux.org/alpine/edge/community' >> /etc/apk/repositories \
        && apk update && apk upgrade \
        && apk add ncurses-libs \
        && rm -rf /var/cache/apk/*

ADD docker/${APP}.tar.gz ${DEPLOY_PATH}

EXPOSE 80

CMD ["/usr/lib/web/bin/web", "foreground"]
